export const CONFIG = {
  // World
  GRID_WIDTH: 200,
  GRID_HEIGHT: 150,
  CELL_RENDER_SIZE: 4,

  // Pheromones
  EVAPORATION_RATE: 0.992,
  DIFFUSION_RATE: 0.15,
  MAX_PHEROMONE: 100,
  PHEROMONE_BRIGHTNESS: 4,

  // Agents
  MAX_AGENTS: 2000,
  INITIAL_AGENTS: 50,
  AGENT_INITIAL_ENERGY: 200,
  AGENT_ENERGY_DRAIN: 0.05,
  AGENT_MAX_AGE: 4000,

  // Colony
  INITIAL_COLONY_ENERGY: 500,
  COLONY_ENERGY_PER_FOOD: 10,
  REPRODUCTION_COST: 30,
  REPRODUCTION_THRESHOLD: 100,
  COLONY_DRAIN_PER_AGENT: 0.001,

  // Genetics
  MUTATION_RATE: 0.05,
  MUTATION_AMOUNT: 0.1,

  // Food
  DEFAULT_FOOD_AMOUNT: 200,
  RICH_FOOD_AMOUNT: 800,
  FOOD_PICKUP_AMOUNT: 1,
  POISON_DAMAGE: 50,

  // Events
  EVENT_INTERVAL_MIN: 1800,
  EVENT_INTERVAL_MAX: 5400,
  RAIN_EVAPORATION_MULTIPLIER: 0.97,
  RAIN_DURATION: 600,

  // Predator
  PREDATOR_SPEED: 0.7,
  PREDATOR_RADIUS: 6,
  PREDATOR_LIFETIME: 1200,

  // RNG
  DEFAULT_SEED: 0xC0FFEE,
} as const;
